### PR TITLE
Adds the ability to add offset to background position

### PR DESCRIPTION
**Pull request by albertski**
Ran into some issues with the background image.  I would see a black area above the image.  

I used the same formula found [here](https://code.tutsplus.com/tutorials/a-simple-parallax-scrolling-technique--net-27641) and it seems to work better:

```
var yPos = -($window.scrollTop() / $bgobj.data('speed'));
```

Not sure if it was just me but that worked a lot better. 

Also, needed the ability to add a little offset so the image displays in the position I would like it to show.  I added an offset field that lets you control it.

### CODE REVIEW

**Review by thejimbirch — COMMENTED** [review]
In general, when Drupal exports yaml files, I believe that the children of items are in alphabetical order. 
 Their position in Drupal can be ordered with the weight option.

In this case, `dependencies > config` and `content > field_name` should be re-ordered.

**Comment by albertski** [comment]
Good point. I made those fixes.

**Comment by thejimbirch** [comment]
Excellent!  Chrissy and I will review in the morning.  She handled the Javascript for this module.

**Review by christine-harder — COMMENTED** [review]
The changes in xeno-hero.js look great. It is a lot cleaner.

**Comment by thejimbirch** [comment]
@albertski I made some changes to the template.  Please review.  If you approve, I will ask @christine-harder to merge the PR.

**Comment by albertski** [comment]
@thejimbirch Your changes look good and I tested and they worked.

Still not sure if you are required to set a default value like you do in php. I'm thinking you don't have to in Twig but jut incase created a question on [Drupal Answers.](https://drupal.stackexchange.com/questions/243962/do-i-have-to-set-a-default-value-to-a-variable-in-twig)

**Comment by thejimbirch** [comment]
We got good feedback on [Drupal Answers](https://drupal.stackexchange.com/questions/243962/do-i-have-to-set-a-default-value-to-a-variable-in-twig) that our solution is valid.

@christine-harder Let me know when you have availability and we can complete this Pull Request.

**Comment by christine-harder** [comment]
Pull request is merged  :+1:

**Pull request merged**
